spring: 
  application:
    name: friendsnet
  datasource: 
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    url: jdbc:h2:~/db_friendsnet;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
   org.springframework: INFO
server:
  port: 8090